version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
  server:
    build: .
    container_name: server
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongo
    links:
      - mongo